version: '3'

services:
  notebook:
    build: .
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=inkitt
    ports:
      - 8888:8888

  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=inkitt
    ports:
      - 5432:5432
